window.FG_PRODUCTS = [
  {
    slug: 'metas', cover: 'img/cover-meta.jpg', name: 'Metas',
    desc: 'Metas y arcos inflables para eventos, carreras y activaciones.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 5 hasta 12 m de ancho, además de fabricación a medida.',
      'Gráfica personalizada a todo color con tu logo y colores de marca.',
      'Fabricadas en tela PVC de alta resistencia, disponible en variedad de colores.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/meta-1.jpg', 'img/meta-2.jpg', 'img/meta-3.jpg', 'img/meta-4.jpg', 'img/meta-5.jpg', 'img/meta-6.jpg', 'img/meta-7.jpg', 'img/meta-8.jpg', 'img/meta-9.jpg', 'img/meta-10.jpg'],
  },
  {
    slug: 'cilindros', cover: 'img/cover-cilindros.png', name: 'Cilindros',
    desc: 'Cilindros inflables para publicidad y puntos de venta.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 2 hasta 10 m de altura, además de fabricación a medida.',
      'Gráfica personalizada a todo color con tu logo y colores de marca.',
      'Fabricados en tela PVC de alta resistencia, disponible en variedad de colores.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/cil-1.jpg', 'img/cil-2.jpg', 'img/cil-3.jpg', 'img/cil-4.jpg', 'img/cil-5.jpg', 'img/cil-6.jpg', 'img/cil-7.jpg', 'img/cil-8.jpg', 'img/cil-9.jpg', 'img/cil-10.jpg'],
  },
  {
    slug: 'peras', cover: 'img/cover-peras.png', name: 'Peras',
    desc: 'Peras publicitarias de gran altura para destacar tu marca desde lejos.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 3 hasta 8 m de altura, además de fabricación a medida.',
      'Gráfica personalizada a todo color con tu logo y colores de marca.',
      'Fabricadas en tela PVC de alta resistencia en variedad de colores existentes.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/pera-1.jpg', 'img/pera-2.jpg', 'img/pera-3.png', 'img/pera-4.png', 'img/pera-5.png', 'img/pera-6.png', 'img/pera-7.png', 'img/pera-8.png', 'img/pera-9.png', 'img/pera-10.png'],
  },
  {
    slug: 'pelotas', cover: 'img/cover-pelotas.jpg', name: 'Pelotas',
    desc: 'Pelotas inflables para publicidad, eventos y activaciones.',
    kicker: 'Inflables a medida',
    features: [
      'De aire retenido para lanzar al público o decoración. Con turbina para publicidad fija y anclada.',
      'Medidas estándar de 1 a 4 m con aire retenido y de 2 a 10 m con turbina.',
      'Gráfica personalizada a todo color con tu logo y colores de marca.',
      'Fabricadas en tela PVC, disponible en distintos colores según la modalidad.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/pelota-1.png', 'img/pelota-2.jpg', 'img/pelota-3.jpg', 'img/pelota-4.jpg', 'img/pelota-5.jpg', 'img/pelota-6.jpg', 'img/pelota-7.jpg', 'img/pelota-8.jpg', 'img/pelota-9.jpg', 'img/pelota-10.jpg'],
  },
  {
    slug: 'formas', cover: 'img/cover-formas.png', name: 'Formas especiales',
    desc: 'Figuras y formas especiales desarrolladas completamente a medida.',
    kicker: 'Inflables a medida',
    features: [
      'Sujetas a evaluación de factibilidad según tamaño, gráfica y nivel de complejidad.',
      'Fabricación en tipo de tela a definir según las características de cada forma.',
      'Gráfica, curvas y detalles pueden requerir adaptaciones según la complejidad de la forma.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/forma-1.jpg', 'img/forma-2.jpeg', 'img/forma-3.jpeg', 'img/forma-4.jpg', 'img/forma-5.jpg', 'img/forma-6.jpg', 'img/forma-7.jpg', 'img/forma-8.jpg', 'img/forma-9.jpg', 'img/forma-10.jpeg'],
  },
  {
    slug: 'formas-de-productos', cover: 'img/cover-formas-productos.jpg', name: 'Formas de productos',
    desc: 'Réplicas inflables de productos reales para publicidad y activaciones.',
    kicker: 'Inflables a medida',
    features: [
      'Sujetas a evaluación de factibilidad según tamaño, gráfica y nivel de complejidad.',
      'Fabricación en tipo de tela a definir según las características de cada producto.',
      'Gráfica, curvas y detalles pueden requerir adaptaciones según la complejidad del producto.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/cover-formas-productos.jpg'],
  },
  {
    slug: 'galpones', cover: 'img/cover-galpones.png', name: 'Galpones',
    desc: 'Estructuras inflables de gran superficie para múltiples aplicaciones.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 3 × 3 m hasta 12 × 8 m, además de fabricación a medida.',
      'Estructura inflable con turbina de aire constante, sin estructuras metálicas.',
      'Fabricados en tela PVC de alta resistencia, disponible en variedad de colores.',
      'Equipados con puertas, ventanas y sistema eléctrico para iluminación y enchufes.',
      'Ideales para eventos, emergencias, salas de espera y espacios de atención.',
    ],
    photos: ['img/galpon-1.jpg', 'img/galpon-2.jpg', 'img/galpon-3.jpg', 'img/galpon-4.jpg', 'img/galpon-5.jpeg', 'img/galpon-6.jpg', 'img/galpon-7.jpg', 'img/galpon-8.jpg', 'img/galpon-9.png'],
  },
  {
    slug: 'tuneles', cover: 'img/cover-tuneles.png', name: 'Túneles',
    desc: 'Túneles inflables para eventos, accesos y activaciones de marca.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 6 × 3 m hasta 15 × 6 m, además de fabricación a medida.',
      'Estructura inflable con turbina de aire constante, sin estructuras metálicas.',
      'Fabricados en tela PVC de alta resistencia, disponible en variedad de colores.',
      'Gráfica personalizada a todo color por el exterior, con opción de gráfica interior.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/tunel-1.jpg', 'img/tunel-2.png', 'img/tunel-3.jpg', 'img/tunel-4.jpg', 'img/tunel-5.jpg', 'img/tunel-6.jpg', 'img/tunel-7.jpg', 'img/tunel-8.jpg', 'img/tunel-9.jpg'],
  },
  {
    slug: 'carpas-paris', cover: 'img/cover-paris.jpg', name: 'Carpas París',
    desc: 'Carpas de diseño elegante para eventos, ferias y atención de público.',
    kicker: 'Diseño a medida',
    features: [
      'Medidas estándar desde 3 hasta 6 m de ancho.',
      'Estructura metálica resistente con diseño de techo tensado.',
      'Fabricadas en tela PVC de alta resistencia, disponible en variedad de colores.',
      'Gráfica personalizada a todo color con tu logo y colores de marca.',
      'Sistema de anclaje al piso mediante estacas.',
    ],
    photos: ['img/paris-1.jpg', 'img/paris-2.png', 'img/paris-3.jpg', 'img/paris-4.jpg', 'img/paris-5.png', 'img/paris-6.jpg', 'img/paris-7.png', 'img/paris-8.png', 'img/paris-9.jpg', 'img/paris-10.png'],
  },
  {
    slug: 'carpas-pulpos', cover: 'img/cover-pulpos.jpg', name: 'Carpas Pulpos',
    desc: 'Carpas inflables de montaje rápido para eventos, ferias y stands.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar de 4 × 4 m hasta 8 m de diámetro.',
      'Estructura inflable con turbina de aire constante, sin estructuras metálicas.',
      'Fabricadas en tela PVC de alta resistencia o lona poliéster, disponibles en variedad de colores.',
      'Gráfica personalizada a todo color en patas y cenefas.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/pulpo-1.jpg', 'img/pulpo-2.jpg', 'img/pulpo-3.jpg', 'img/pulpo-4.jpg', 'img/pulpo-5.jpg', 'img/pulpo-6.jpg', 'img/pulpo-7.jpg', 'img/pulpo-8.jpg', 'img/pulpo-9.jpg', 'img/pulpo-10.jpeg'],
  },
  {
    slug: 'bailarines', cover: 'img/cover-bailarines.png', name: 'Bailarines',
    desc: 'Bailarines de movimiento constante para publicidad y activaciones.',
    kicker: 'Inflables a medida',
    features: [
      'Disponibles en 3 y 5 m de altura.',
      'Brazos con movimiento libre o controlado, según el efecto deseado.',
      'Fabricados en tela liviana de alta resistencia, disponible en variedad de colores.',
      'Gráfica personalizada a todo color con tu logo y colores de marca.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/bailarin-1.png', 'img/bailarin-2.png', 'img/bailarin-3.png', 'img/bailarin-4.png', 'img/bailarin-5.png', 'img/bailarin-6.png', 'img/bailarin-7.png', 'img/bailarin-8.png', 'img/bailarin-9.png', 'img/bailarin-10.png'],
  },
  {
    slug: 'logos-inflables', cover: 'img/cover-logos.jpg', name: 'Logos inflables',
    desc: 'Logos de empresas desarrollados en formato inflable y a medida.',
    kicker: 'Inflables a medida',
    features: [
      'Diseñados a partir de la forma y gráfica de tu logo, escudo o imagen de marca.',
      'Gráfica personalizada a todo color por ambos lados.',
      'Fabricados en tela PVC de alta resistencia, con base inflable para sustentación.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/cover-logos.jpg'],
  },
  {
    slug: 'globos-con-helio', cover: 'img/cover-globos.jpg', name: 'Globos con helio',
    desc: 'Globos publicitarios con helio para gran visibilidad a distancia.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 2,5 hasta 4 m de diámetro.',
      'Fabricados en tela PVC inflable de color blanco, con fondo a color opcional.',
      'Gráfica personalizada a todo color por ambos lados.',
      'Todo incluido: carga 100% helio, sistema de anclaje, iluminación interior y bolsa de transporte.',
      'Instalación a nivel de piso incluida en Santiago. Sujeta a factibilidad.',
    ],
    photos: ['img/globo-1.jpg', 'img/globo-2.jpg', 'img/globo-3.jpg', 'img/globo-4.jpg', 'img/globo-5.jpg', 'img/globo-6.jpg', 'img/globo-7.jpg', 'img/globo-8.jpg', 'img/globo-9.jpg', 'img/globo-10.jpg'],
  },
  {
    slug: 'pantallas', cover: 'img/cover-pantallas.png', name: 'Pantallas',
    desc: 'Pantallas inflables para proyección en eventos y espacios abiertos.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 5 × 4 m hasta 7,5 × 5,5 m, además de fabricación a medida.',
      'Estructura inflable con turbina de aire constante, sin estructuras metálicas.',
      'Fabricadas en tela PVC de alta resistencia, con superficie blanca para proyección.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/pantalla-1.png', 'img/pantalla-2.jpg', 'img/pantalla-3.jpg', 'img/pantalla-4.jpg', 'img/pantalla-5.jpg'],
  },
  {
    slug: 'cubos-y-rectangulos', cover: 'img/cover-cubos.jpg', name: 'Cubos y Rectángulos',
    desc: 'Cubos y rectángulos inflables, ideales para exhibir gráfica en sus cuatro caras.',
    kicker: 'Inflables a medida',
    features: [
      'Medidas estándar desde 2 hasta 6 m de altura, además de fabricación a medida.',
      'Gráfica personalizada a todo color con tu logo por todas sus caras.',
      'Fabricados en tela PVC de alta resistencia, disponible en variedad de colores.',
      'Todo incluido: turbina, cuerdas de anclaje, estacas y bolsa de transporte.',
      'Fáciles de instalar, desmontar y transportar.',
    ],
    photos: ['img/cubo-1.jpg', 'img/cubo-2.jpg', 'img/cubo-3.jpg', 'img/cubo-4.jpg', 'img/cubo-5.jpg', 'img/cubo-6.jpg', 'img/cubo-7.jpg', 'img/cubo-8.jpg', 'img/cubo-9.jpg', 'img/cubo-10.jpg'],
  },
];

window.FG_FEATURES = [
  'Diseño, fabricación, instalación y mantención realizada por nosotros.',
  'Impresión gráfica a todo color, con tu logo y colores de marca.',
  'Medidas y forma a pedido, sin estructuras metálicas.',
  'Montaje y desmontaje rápido; fáciles de transportar.',
  'Materias primas de alta calidad, con garantía y mantención en nuestros talleres.',
];
